# Generated by Django 3.1.2 on 2020-12-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvApp', '0002_auto_20201212_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
