# Generated by Django 3.0.8 on 2020-08-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.CharField(default='place holder', max_length=255),
            preserve_default=False,
        ),
    ]
