# Generated by Django 3.0.8 on 2020-08-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_model_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
    ]
